//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMovieNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        private static DataModelContainer _instance = null;
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        public static DataModelContainer GetDb()
        {
            if (_instance == null)
            {
                _instance = new DataModelContainer();
            }
            return _instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Movie> MovieSet { get; set; }
        public virtual DbSet<Comment> CommentSet { get; set; }
    }
}
